server:
  port: 10000
spring:
  profiles:
    active: h2  # h2,mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#日志目录
logging:
  file:
    path: ./
    name: ddns4j.log

dns:
  serviceTypes:
    1: aliDynamicDnsStrategyImpl
    2: tencentDynamicDnsStrategyImpl
    3: cloudflareDynamicDnsStrategyImpl
    4: huaweiDynamicDnsStrategyImpl


