server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.30:3306/ddns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#日志目录
logging:
  file:
    path: ./
#自定义配置
aliyun:
  accessKeyId: LTAI5tH3yQeiFNAuEA5aN5ZJ
  accessKeySecret: aaT7phpgYHu3gWNgKHjwvq6Wr9wIhP
  domainName: sssd.top
  RR: k8s
  recordType: AAAA
cron: 0 0/1 * * * ?